//Languege Changing System:

const langAr = [
  { title: ' ' },
  { JoinLink: '' },
  { SupportLink: '' },
  { InfoLink: '' },
  { ICText: '' },
  { ItallStartstext: '' },
  { LongIntroQ: '' },
  { LongIntroText: '' },
  { ZZIMainTitle: '' },
  { LeftSectTitle1: '' },
  { LeftSectText1: '' },
  { RightSectTitle1: '' },
  { RightSectText1: '' },
  { LeftSectTitle2: '' },
  { LeftSectText2: '' },
  { RightSectTitle2: '' },
  { RightSectText2: '' },
  { ChangerButton: '' },
];
const langFr = [
  { title: ' ' },
  { JoinLink: '' },
  { SupportLink: '' },
  { InfoLink: '' },
  { ICText: '' },
  { ItallStartstext: '' },
  { LongIntroQ: '' },
  { LongIntroText: '' },
  { ZZIMainTitle: '' },
  { LeftSectTitle1: '' },
  { LeftSectText1: '' },
  { RightSectTitle1: '' },
  { RightSectText1: '' },
  { LeftSectTitle2: '' },
  { LeftSectText2: '' },
  { RightSectTitle2: '' },
  { RightSectText2: '' },
  {},
];
